title: "James Baker"
author:
  name: James Baker
description: >
  A personal site, where you can read whatever I feel like writing ✍️

timezone: Europe/London
lang: en-GB

remote_theme: "jekyll/minima@bf9ef98"

plugins:
  - jekyll-feed
  - jekyll-remote-theme

minima:
  skin: classic
  show_excerpts: true
  nav_pages:
    - now.md
  social_links:
    - title: View on GitHub
      icon: github
      url: "https://github.com/RusticFlare/github-pages-blog"

permalink: pretty

exclude:
  - LICENSE
